### ISSUE TITLE
Over CPU and RAM usage while downloading files from S3

### ISSUE THREAD

**Issue by Toanzzz** [nmcapule/metabox-go#4]
While downloading file from S3, the CPU & memory usage got extremely high, 100% and around 2GB+ for ~250MB file.
This is pretty weird consider it only downloading, not yet come to decompressing it yet.

So as this problem exists I couldn't make it run inside limited environment like small EC2 instance or inside docker container

**Comment by nmcapule** [comment]
HI! Can you provide more context? Afaik memory leaks are only relevant on long-running applications.

go-metabox is a CLI tool that exits as soon as it's done doing its job. Once the tool has exited, it is up to the Go runtime to cleanup memory. The OS itself also tracks memory allocations of a program, so if the program has exited -- the OS will also cleanup the dangling bits.

Are you encountering OOM errors?

**Comment by Toanzzz** [comment]
Sorry, I was in rush and didn't describe the problem properly. I updated the PR and description

**Comment by Toanzzz** [comment]
Btw I really glad that this tool haven't abandoned yet 😀
Willing to help regarding this if you want (maybe this weekend)

**Comment by nmcapule** [comment]
No prob! Can you post your *.metabox.yaml file for reference? Make sure that there are no sensitive values for `access_key_id` and `secret_access_key` though :)

**Comment by Toanzzz** [comment]
sure, here it is
```yaml
version: 0.1
workspace:
  user_identifier: "${TARGET_USER}"
  tags_generator: ["author:${TARGET_USER}"]
target:
  prefix_path: ./dumps
  includes: ["**/*"]
  excludes: [".git/"]
backups:
  - driver: s3
    s3:
      access_key_id: ${AWS_ACCESS_KEY_ID}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      region: ${AWS_DEFAULT_REGION}
      bucket: ${AWS_S3_BUCKET}
      prefix_path: ${AWS_S3_PREFIX}

```
